# Generated by Django 5.0.3 on 2024-03-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='yoo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blog')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.DeleteModel(
            name='ModeratorFeedback',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.category'),
        ),
    ]
