# Generated by Django 5.0.3 on 2024-03-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_comment_blog_rename_post_like_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(related_name='blogs', to='blog.category'),
        ),
    ]
