version: "3.9"

services:
  app:
    image: moderation-microservice6:v1.0.0
    build: 
      context: .
    volumes:
      - .:/moderation_microservice
    ports:
       - "8000:8000"
    env_file:
      - ./digital_magazine/.env
    container_name: moderation-microservice6